Tarea2-3
DJAA12/Anchia-Finance pull request #1
Opened 2024-10-21 03:17 UTC by DJAA12

Se realizaron los siguientes cambios en el branch tarea2-3:
- Diseño de los layouts de los activities.
- Implementación de las opciones de menú en la pantalla principal.
- Configuración de las llamadas entre activities (navegación entre pantallas al hacer clic).
- Definición de las clases entities.
- Definición de las clases model.
- Definición de la clase ManagerMemory.
- Definición de la interface.
- Definición de la clase util.

2024-10-21 03:23 UTC, DJAA12 commented
Se ha completado los requerimientos solicitados para la tarea 2-3. Hago entrega de lo requerido y quedo al pendiente por si necesita que realice algún cambio o mejora.

2024-10-25 01:39 UTC, ebarahonautn requested changes
El proyecto no tiene un formato de kotlin, no tiene clases ni interface, por favior corregirlo.

2024-10-25 07:01 UTC, DJAA12 commented
@ebarahonautn 
Profe, disculpe por los inconvenientes presentados. Se me había dañado el proyecto y no me había dado cuenta. Ya está corregido lo que se solicitaba. Gracias de antemano, quedo pendiente de su revisión.

2024-10-25 19:50 UTC, ebarahonautn approved these changes

2024-10-25 19:50 UTC, merged